# -*- coding: utf-8 -*-
"""Algorithmof Data Science-Deliverable 1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jpgTQAhm6Q2SgKpmasgd9XOFb0Mv2N79
"""

user_prompt = "I have just been on an international flight, can I come back home to hold my 1-month-old newborn?"
url_to_check = "https://www.bhtp.com/blog/when-safe-to-travel-with-newborn/"

result = rate_url_validity(user_prompt, url_to_check)
print(result)

user_prompt = "I have just been on an international flight, can I come back home to hold my 1-month-old newborn?"
url_to_check = "https://www.quora.com/How-soon-can-I-take-my-newborn-with-me-when-I-fly-internationally"

result = rate_url_validity(user_prompt, url_to_check)
print(result)